name: Ubuntu-Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
    - name: Upload Sample Program
      uses: actions/upload-artifact@v3
      with: 
        name: Sample Program
        path: sample
  
    - name: Test glxinfo
      run: |
        sudo apt install -y mesa-utils xvfb
        xvfb-run glxinfo
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: xvfb-run ctest -C ${{env.BUILD_TYPE}} -T test --output-on-failure
    
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with: 
        name: Build
        path: .
      
