name: Ubuntu-Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload Ubuntu Sample Program
      uses: actions/upload-artifact@v3
      with: 
        name: linux-x64
        path: build/rey/bin/
    - name: Test glxinfo
      run: xvfb-run glxinfo
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: xvfb-run ctest -C ${{env.BUILD_TYPE}} -T test --output-on-failure
      
  build-windows-:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Ninja
      run: choco install -y mingw
    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j4
    - name: Upload Windows Sample Program
      uses: actions/upload-artifact@v3
      with: 
        name: windows-x64
        path: build/rey/bin/
      
